### ISSUE TITLE
Tor Browser (Flatpak) Auto update doesn't work anymore after i think 13.0 update

### ISSUE THREAD

**Issue by harbor6688** [torproject/torbrowser-launcher#721]
Before the Tor Browser would just update normally together when a new update dropped and in settings you could fine an update search button said button is now missing in the torbrowser launched by the Tor Browser launcher it also seems like it doesn't autoupdate anymore since i had to completly reinstall it trough the launcher to get the newest version.

**Comment by AsciiWolf** [comment]
It did auto update from 13.0 to 13.0.1 on my machine without any issues.

**Comment by harbor6688** [comment]
> It did auto update from 13.0 to 13.0.1 on my machine without any issues.

could have sworn it didn't update can you see the check update button in settings where you can check for updates? For me that is missing completly now

**Comment by AsciiWolf** [comment]
The update button also seems to be missing on my installation, however it did auto update without issues when the new Tor Browser version got released.

**Comment by DUBDUBHUB** [comment]
harbor6688 yup I have the same issue 
![image](https://github.com/torproject/torbrowser-launcher/assets/150360681/9ef403ca-2583-403b-b8d9-5bab51830c43)

**Comment by AsciiWolf** [comment]
@DUBDUBHUB This seems to be a different issue (since you have an older, 12.0.5, version).

**Comment by DUBDUBHUB** [comment]
Ok, thanks is there any way to fix it ? I tried installing and reinstalling it and so far nothing works fro me

**Comment by AsciiWolf** [comment]
Sorry, I have no idea. Your issue is most likely caused by Tor Browser itself, not torbrowser-launcher.

**Comment by DUBDUBHUB** [comment]
k anyways thanks for your help man

**Comment by harbor6688** [comment]
The really weird part about this is that this doesn't happen with the normal TBB binary even if you launch TBB directly trough the .desktop file located at var/app/com.github.micahflee.torbrowser-launcher/data/torbrowser/tbb/x86_64/tor-browser/Browser/start-tor-browser.desktop it will start normally and the update process will be available there so the issue has to be from the tbl instead

**Comment by harbor6688** [comment]
> The really weird part about this is that this doesn't happen with the normal TBB binary even if you launch TBB directly trough the .desktop file located at .var/app/com.github.micahflee.torbrowser-launcher/data/torbrowser/tbb/x86_64/tor-browser/Browser/start-tor-browser.desktop it will start normally and the update process will be available there so the issue has to be from the tbl instead

In short either a recent change was made deliberatly for the tbb to act like this when launched trough the tb-l (i could not think of any advantage for that) or a recent change has made it surface can't see anything too deliberate trough in the latest commits trough

**Comment by boklm** [comment]
There was no deliberate change to prevent updates when run in
torbrowser-launcher.

If you set the pref `app.update.log` to true, the Browser Console
should have some logs that can help understand what is happenning.

**Comment by AsciiWolf** [comment]
Interesting, I can reproduce this issue on my other computer also running the Flatpak version of torbrowser-launcher. I can also reproduce it after removing the data directory and letting torbrowser-launcher create a clean profile.

This did appear in the Tor Browser console log after opening the "About Tor Browser" window:
```
Error: Invalid autocomplete selectedIndex [AutoCompleteChild.sys.mjs:111:13](resource://gre/actors/AutoCompleteChild.sys.mjs)
    get selectedIndex resource://gre/actors/AutoCompleteChild.sys.mjs:111
AUS:AUM AppUpdater:check -AppConstants.MOZ_UPDATER=truethis.#updateDisabledByPackage: true
```

**Comment by AsciiWolf** [comment]
Anyway, we should probably resolve this issue before releasing a new torbrowser-launcher.

**Comment by AsciiWolf** [comment]
Could someone try starting the Tor Browser manually **from inside the Flatpak**?

```
$ flatpak run --command=sh com.github.micahflee.torbrowser-launcher
$ cd ~/.var/app/com.github.micahflee.torbrowser-launcher/data/torbrowser/tbb/x86_64/tor-browser
$ ./Browser/start-tor-browser --detach
```

In my case, the autoupdater seems to have the same problem when Tor Browser is started manually this way.

**Comment by AsciiWolf** [comment]
So, yeah, if I run the same Tor Browser instance outside of the Flatpak sandbox, the auto update works fine. But if I run it inside the Flatpak sandbox, the auto update function seems to be missing from the GUI.

It looks like that Tor Browser probably depends on a certain lib version/ABI for the auto update to work correctly and this changed when the Flatpak runtime got updated. This is however **not a torbrowser-launcher issue** and **has to be fixed in the Tor Browser itself**.

@boklm Do you have any idea what Tor Browser uses for its auto update functionality?

**Comment by AsciiWolf** [comment]
Well, this issue will be trickier than I thought. Downgrading the runtime did not help, so the problem is not related to the Flatpak runtime version. However, it happens only in the Flatpak sandbox and it used to work fine before TBB 13.0 or 13.0.1.

**Comment by boklm** [comment]
> Interesting, I can reproduce this issue on my other computer also running the Flatpak version of torbrowser-launcher. I can also reproduce it after removing the data directory and letting torbrowser-launcher create a clean profile.
> 
> This did appear in the Tor Browser console log after opening the "About Tor Browser" window:
> ```
> Error: Invalid autocomplete selectedIndex [AutoCompleteChild.sys.mjs:111:13](resource://gre/actors/AutoCompleteChild.sys.mjs)
>     get selectedIndex resource://gre/actors/AutoCompleteChild.sys.mjs:111
> AUS:AUM AppUpdater:check -AppConstants.MOZ_UPDATER=truethis.#updateDisabledByPackage: true
> ```

From this error it looks like the mozilla updater (which Tor Browser is
using) is now detecting that it has been installed by a package and
disables updates in this case:
https://searchfox.org/mozilla-central/source/toolkit/mozapps/update/AppUpdater.sys.mjs#404

**Comment by boklm** [comment]
I've opened a issue to fix this in Tor Browser:
https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/42293

**Comment by mooreye** [comment]
3 weeks since opened issue, are they working on it? This is really worrisome, TBB not updating...

**Comment by AsciiWolf** [comment]
@mooreye Please, if possible, comment on this in the [upstream TBB ticket](https://github.com/torproject/torbrowser-launcher/issues/721#issuecomment-1825471099).

I was sadly not able to find any usable workaround yet so this needs to be fixed in tor-browser upstream, not torbrowser-launcher Flatpak.

**Comment by harbor6688** [comment]
Issue is now resolved with the newest tor browser version

**Comment by Francewhoa** [comment]
Same challenge here with Tor Browser (TB) 13.0.9. Which was installed using this [Tor Browser Launcher](https://flathub.org/apps/org.torproject.torbrowser-launcher) (TBL) 0.3.7.

What worked for us was to, just for one time, launch TB without using Flatpak. This automatically triggered the update. After the update from 13.0.9 to 13.0.14, all future updates are likely to be successful using TB launched with Flatpak.

Detailed steps and attribution at https://github.com/flathub/org.torproject.torbrowser-launcher/issues/5#issuecomment-2061913852
