### ISSUE TITLE
Tor browser refuses to connect and update [old tor version 12.0.5, haven't updated it in quiet a while]

### ISSUE THREAD

**Issue by DUBDUBHUB** [torproject/torbrowser-launcher#722]
OS: **Ubuntu 22.04.2 LTS x86_64**

Host: **VirtualBox 1.2**

Kernel: **6.2.0-36-generic**

Packages: **1787 (dpkg), 19 (flatpak), 12 (snap)**

Shell: **/bin/bash 5.1.16**

DE: **GNOME 42.5**
I tried to install and reinstall and other things but nothing works so far I just get this, (I use torbrowser-launcher for this since directly installing tor doesn't work for me I tried various methods it just refuse to budge)
![image](https://github.com/torproject/torbrowser-launcher/assets/150360681/3ba5c8c8-cd33-4bb2-900e-db2cfdfd9b92)

**Comment by boklm** [comment]
To try to debug this you can set the pref `app.update.log` to true, and the Browser Console should have some logs about what it's doing to check if there is an update.

Otherwise you can remove your torbrowser directory and let torbrowser-launcher download a new one.

**Comment by DUBDUBHUB** [comment]
Hey thanks, it worked
